# Generated by Django 5.2.4 on 2025-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_remove_swaprequest_timestamp_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
