# Generated by Django 5.2.4 on 2025-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_remove_userprofile_image_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
